spring.application.name=promptswave
server.port=${PORT:8085}

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/promptswave?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:6001}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

# JWT
app.jwt.secret=${JWT_SECRET:promtvault-super-secret-jwt-key-must-be-at-least-64-characters-long-for-hs512}
app.jwt.access-expiration-ms=604800000
app.jwt.refresh-expiration-ms=2592000000


spring.mail.host=${MAIL_HOST:smtpout.secureserver.net}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:shradheyrastogi@promptswave.com}
spring.mail.password=${MAIL_PASSWORD:902702814@Sr1}
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000



# App URLs
app.base-url=${APP_BASE_URL:http://localhost:8085}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# Token blacklist cleanup every hour
token.blacklist.cleanup-interval-ms=3600000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html